// <auto-generated />
using System;
using CognitiveLedger.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CognitiveLedger.Data.Database.Migrations
{
    [DbContext(typeof(CognitiveLedgerDbContext))]
    [Migration("20260914235646_UseSnakeCaseColumnNames")]
    partial class UseSnakeCaseColumnNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CognitiveLedger.Data.Models.CreditCard.CreditCardStatement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("account_name");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<decimal>("Fees")
                        .HasColumnType("numeric")
                        .HasColumnName("fees");

                    b.Property<decimal>("InterestCharged")
                        .HasColumnType("numeric")
                        .HasColumnName("interest_charged");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issuer");

                    b.Property<decimal>("NewBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("new_balance");

                    b.Property<decimal>("PreviousBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("previous_balance");

                    b.Property<string>("SourceDocumentSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_document_sha256");

                    b.Property<DateOnly>("StatementPeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("statement_period_end");

                    b.Property<DateOnly>("StatementPeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("statement_period_start");

                    b.Property<decimal>("TotalOtherCredits")
                        .HasColumnType("numeric")
                        .HasColumnName("total_other_credits");

                    b.Property<decimal>("TotalPayments")
                        .HasColumnType("numeric")
                        .HasColumnName("total_payments");

                    b.Property<decimal>("TotalPurchases")
                        .HasColumnType("numeric")
                        .HasColumnName("total_purchases");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("SourceDocumentSha256")
                        .IsUnique()
                        .HasFilter("source_document_sha256 IS NOT NULL");

                    b.HasIndex("Issuer", "AccountName", "StatementPeriodEnd");

                    b.ToTable("statements", (string)null);
                });

            modelBuilder.Entity("CognitiveLedger.Data.Models.CreditCard.CreditCardTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsCredit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_credit");

                    b.Property<string>("Merchant")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("merchant");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<long>("StatementId")
                        .HasColumnType("bigint")
                        .HasColumnName("statement_id");

                    b.Property<DateOnly?>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("StatementId", "Sequence")
                        .IsUnique();

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("CognitiveLedger.Data.Models.CreditCard.StatementProcessingAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AiModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ai_model");

                    b.Property<string>("AiProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ai_provider");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<int>("CorrectedRowCount")
                        .HasColumnType("integer")
                        .HasColumnName("corrected_row_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long?>("DurationMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_milliseconds");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<int?>("ExtractedTransactionCount")
                        .HasColumnType("integer")
                        .HasColumnName("extracted_transaction_count");

                    b.Property<int>("IgnoredRowCount")
                        .HasColumnType("integer")
                        .HasColumnName("ignored_row_count");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<long?>("StatementId")
                        .HasColumnType("bigint")
                        .HasColumnName("statement_id");

                    b.Property<string>("StatementType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("statement_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("StatementId");

                    b.ToTable("processing_audits", (string)null);
                });

            modelBuilder.Entity("CognitiveLedger.Data.Models.CreditCard.CreditCardTransaction", b =>
                {
                    b.HasOne("CognitiveLedger.Data.Models.CreditCard.CreditCardStatement", "Statement")
                        .WithMany("Transactions")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("CognitiveLedger.Data.Models.CreditCard.StatementProcessingAudit", b =>
                {
                    b.HasOne("CognitiveLedger.Data.Models.CreditCard.CreditCardStatement", "Statement")
                        .WithMany("ProcessingAudits")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("CognitiveLedger.Data.Models.CreditCard.CreditCardStatement", b =>
                {
                    b.Navigation("ProcessingAudits");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
