// <auto-generated />
using System;
using CognitiveLedger.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CognitiveLedger.Data.Database.Migrations
{
    [DbContext(typeof(CognitiveLedgerDbContext))]
    [Migration("20260914221201_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CognitiveLedger.Data.Models.CreditCard.CreditCardStatement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("Fees")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InterestCharged")
                        .HasColumnType("numeric");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("NewBalance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PreviousBalance")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("StatementPeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StatementPeriodStart")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalOtherCredits")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalPayments")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalPurchases")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Issuer", "AccountName", "StatementPeriodEnd");

                    b.ToTable("statements", (string)null);
                });

            modelBuilder.Entity("CognitiveLedger.Data.Models.CreditCard.CreditCardTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsCredit")
                        .HasColumnType("boolean");

                    b.Property<string>("Merchant")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<long>("StatementId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StatementId", "Sequence")
                        .IsUnique();

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("CognitiveLedger.Data.Models.CreditCard.StatementProcessingAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AiModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AiProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CorrectedRowCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<long?>("DurationMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("ExtractedTransactionCount")
                        .HasColumnType("integer");

                    b.Property<int>("IgnoredRowCount")
                        .HasColumnType("integer");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("StatementId")
                        .HasColumnType("bigint");

                    b.Property<string>("StatementType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("StatementId");

                    b.ToTable("processing_audits", (string)null);
                });

            modelBuilder.Entity("CognitiveLedger.Data.Models.CreditCard.CreditCardTransaction", b =>
                {
                    b.HasOne("CognitiveLedger.Data.Models.CreditCard.CreditCardStatement", "Statement")
                        .WithMany("Transactions")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("CognitiveLedger.Data.Models.CreditCard.StatementProcessingAudit", b =>
                {
                    b.HasOne("CognitiveLedger.Data.Models.CreditCard.CreditCardStatement", "Statement")
                        .WithMany("ProcessingAudits")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("CognitiveLedger.Data.Models.CreditCard.CreditCardStatement", b =>
                {
                    b.Navigation("ProcessingAudits");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
