// <auto-generated />
using System;
using CognitiveLedger.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CognitiveLedger.Data.Database.Migrations
{
    [DbContext(typeof(CognitiveLedgerDbContext))]
    partial class CognitiveLedgerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("CognitiveLedger.Data.Models.CreditCardAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFourDigits")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CreditCardAccounts");
                });

            modelBuilder.Entity("CognitiveLedger.Data.Models.CreditCardStatement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AvailableCredit")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ClosingDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FeesTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InterestTotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MinimumPaymentDue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NewBalance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PaymentDueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PaymentsAndCredits")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PeriodEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PeriodStartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PreviousBalance")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PurchasesTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("SourceFileHash");

                    b.ToTable("CreditCardStatements");
                });

            modelBuilder.Entity("CognitiveLedger.Data.Models.CreditCardTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AiConfidence")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("MerchantName")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OriginalAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalCurrencyCode")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourcePageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSequence")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StatementId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserNotes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StatementId");

                    b.ToTable("CreditCardTransactions");
                });

            modelBuilder.Entity("CognitiveLedger.Data.Models.CreditCardStatement", b =>
                {
                    b.HasOne("CognitiveLedger.Data.Models.CreditCardAccount", "Account")
                        .WithMany("Statements")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CognitiveLedger.Data.Models.CreditCardTransaction", b =>
                {
                    b.HasOne("CognitiveLedger.Data.Models.CreditCardStatement", "Statement")
                        .WithMany("Transactions")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("CognitiveLedger.Data.Models.CreditCardAccount", b =>
                {
                    b.Navigation("Statements");
                });

            modelBuilder.Entity("CognitiveLedger.Data.Models.CreditCardStatement", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
